joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 30

rover_arm:
    type: position_controllers/JointTrajectoryController
    joints:
      - arm_foot_cyl__arm_link_01_joint
      - arm_link_01__arm_link_02_joint
      - arm_link_02__arm_link_03_joint
      - arm_link_03__arm_link_03a_joint
      - arm_link_03a__arm_link_04_joint

    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        arm_foot_cyl__arm_link_01_joint: {trajectory: 0.1, goal: 0.1}
        arm_link_01__arm_link_02_joint: {trajectory: 0.1, goal: 0.1}
        arm_link_02__arm_link_03_joint: {trajectory: 0.1, goal: 0.1}
        arm_link_03__arm_link_03a_joint: {trajectory: 0.1, goal: 0.1}
        arm_link_03a__arm_link_04_joint: {trajectory: 0.1, goal: 0.1}

    stop_trajectory_duration: 0.5
    state_publish_rate:  15
    action_monitor_rate: 10
