controller_list:
  - name: fake_rover_controller
    joints:
      - chassis_link__front_left_steer
      - front_left_steer__front_left_wheel
      - chassis_link__front_right_steer
      - front_right_steer__front_right_wheel
      - rear_left_steer__rear_left_wheel
      - rear_right_steer__rear_right_wheel
  - name: fake_arm_controller
    joints:
      - arm_foot_cyl__arm_link_01_joint
      - arm_link_01__arm_link_02_joint
      - arm_link_02__arm_link_03_joint
      - arm_link_03__arm_link_03a_joint
      - arm_link_03a__arm_link_04_joint