# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_foot_cyl__arm_link_01_joint
    - arm_link_01__arm_link_02_joint
    - arm_link_02__arm_link_03_joint
    - arm_link_03__arm_link_03a_joint
    - arm_link_03a__arm_link_04_joint
    - chassis_link__front_left_steer
    - front_left_steer__front_left_wheel
    - chassis_link__front_right_steer
    - front_right_steer__front_right_wheel
    - rear_left_steer__rear_left_wheel
    - rear_right_steer__rear_right_wheel
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: effort_controllers/JointPositionController
  joints:
    - arm_foot_cyl__arm_link_01_joint
    - arm_link_01__arm_link_02_joint
    - arm_link_02__arm_link_03_joint
    - arm_link_03__arm_link_03a_joint
    - arm_link_03a__arm_link_04_joint
  gains:
    arm_foot_cyl__arm_link_01_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_link_01__arm_link_02_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_link_02__arm_link_03_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_link_03__arm_link_03a_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_link_03a__arm_link_04_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1