<?xml version="1.0"?>
<robot name="steer" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Begin - Include -->
  <xacro:include filename="$(find rover_desc_pkg)/urdf/robot_parameters.xacro"/>
  <xacro:include filename="$(find rover_desc_pkg)/urdf/links_joints.xacro"/>
  <!-- End - Include -->

  <xacro:macro name="steer" params="fr lr parent type translateX translateY"> <!-- fr: front, rear; lr: left, right -->
    <!-- Compute steer position based on its location -->
    <xacro:property name="steer_x" value="${translateX * world_x_origin_to_steer_x_origin}" scope="local"/>
    <xacro:property name="steer_y" value="${translateY * world_y_origin_to_steer_y_origin}" scope="local"/>
    <xacro:property name="steer_z" value="${wheel_radius + steer_z_origin_to_wheel_z_origin}" scope="local"/>

    <xacro:if value="${fr == 'rear'}">
      <xacro:property name="steer_x"
                      value="${translateX * (world_x_origin_to_steer_x_origin + 0.063)}"
                      scope="local"/>
    </xacro:if>

    <!-- Decide steer mesh file based on its location -->
    <xacro:if value="${lr == 'right'}">
      <xacro:property name="mesh_file" value="package://rover_desc_pkg/meshes/rover_steer_r.dae"/>
      <xacro:property name="steer_z"
                      value="${wheel_radius + steer_z_origin_to_wheel_z_origin + 0.0032}"
                      scope="local"/>
    </xacro:if>
    <xacro:if value="${lr == 'left'}">
      <xacro:property name="mesh_file" value="package://rover_desc_pkg/meshes/rover_steer_l.dae"/>
      <!-- <xacro:property name="steer_z"
                           value="${wheel_radius + steer_z_origin_to_wheel_z_origin}"
                           scope="local"/> -->
    </xacro:if>

    <!-- Link description -->
    <xacro:m_link_mesh name="${fr}_${lr}_steer"
                       color="darkgray"
                       origin_rpy="0 0 0"
                       origin_xyz="0 0 0"
                       mass="1.0"
                       ixx="0.0001" ixy="0.0" ixz="0.0"
                       iyy="0.0001" iyz="0.0"
                       izz="0.0001"
                       meshfile="${mesh_file}"
                       meshscale="1 1 1"/>

    <gazebo reference="${fr}_${lr}_steer">
      <material>Gazebo/Grey</material>
    </gazebo>

    <!-- Joint description -->
    <xacro:if value="${type == 'fixed'}">
      <xacro:m_joint_fixed name="${parent}__${fr}_${lr}_steer"
                           origin_rpy="0 0 0" origin_xyz="${steer_x} ${steer_y} ${steer_z}"
                           parent="${parent}" child="${fr}_${lr}_steer"/>
    </xacro:if>
    <xacro:if value="${type == 'revolute'}">
      <xacro:m_joint_rev name="${parent}__${fr}_${lr}_steer"
                         axis_xyz="0 0 1"
                         origin_rpy="0 0 0" origin_xyz="${steer_x} ${steer_y} ${steer_z}"
                         parent="${parent}" child="${fr}_${lr}_steer"
                         limit_e="100" limit_l="-${M_PI/2}" limit_u="${M_PI/2}" limit_v="100"/>
    </xacro:if>

    <!-- Transmission is important to link the joints and the controller -->
    <!-- <transmission name="${fr}_${lr}_steer_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${fr}_${lr}_steer_joint"/>
      <actuator name="${fr}_${lr}_steer_joint_motor">
          <hardwareInterface>EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission> -->
  </xacro:macro>
</robot>
