<?xml version="1.0"?>
<robot name="steer" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Begin - Include -->
    <xacro:include filename="$(find rover_desc_pkg)/urdf/robot_parameters.xacro"/>
    <xacro:include filename="$(find rover_desc_pkg)/urdf/links_joints.xacro"/>
    <!-- End - Include -->

    <xacro:macro name="steer" params="fr lr type parent translateX translateY"> <!-- fr: front, rear; lr: left, right -->
        <m_joint name="${parent}__${fr}_${lr}_steer" type="${type}"
                 axis_xyz="0 0 0"
                 origin_rpy="0 0 0" origin_xyz="0 0 0"
                 parent="${parent}" child="${fr}_${lr}_steer"
                 limit_e="0" limit_l="0" limit_u="0" limit_v="0"/>

        <m_link_mesh name="${fr}_${lr}_steer"
                     color="White"
                     origin_rpy="0 0 0" origin_xyz="0 0 ${(chassis_height/2) + 0.1397}"
                     mass="1.0"
                     ixx="0.0001" ixy="0.0" ixz="0.0"
                     iyy="0.0001" iyz="0.0"
                     izz="0.0001"
                     meshfile="package://rover_desc_pkg/meshes/rover_steer.dae"
                     meshscale="1 1 1"/>

        <gazebo reference="${fr}_${lr}_steer">
            <visual name="${fr}_${lr}_steer_visual">
                <material>
                    <ambient>0.5 0.5 0.5 1.0</ambient>
                    <specular>0.8 0.8 0.8 0.1</specular>
                    <diffuse>1.0 1.0 1.0 1.0</diffuse>
                </material>
            </visual>
            <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <!-- Transmission is important to link the joints and the controller -->
        <!-- <transmission name="${fr}_${lr}_steer_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${fr}_${lr}_steer_joint"/>
            <actuator name="${fr}_${lr}_steer_joint_motor">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission> -->
    </xacro:macro>
</robot>
