<?xml version="1.0"?>
<robot name="steer" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Begin - Include -->
    <xacro:include filename="$(find rover_desc_pkg)/urdf/robot_parameters.xacro"/>
    <xacro:include filename="$(find rover_desc_pkg)/urdf/links_joints.xacro"/>
    <!-- End - Include -->

    <xacro:macro name="steer_f" params="lr parent translateX translateY"> <!-- lr: left, right -->
        <m_joint name="${parent}__front_${lr}_steer" type="fixed"
                 axis_xyz="0 0 0"
                 origin_rpy="0 0 0" origin_xyz="0 0 0"
                 parent="${parent}" child="front_${lr}_steer"
                 limit_e="0" limit_l="0" limit_u="0" limit_v="0"/>

        <m_link_mesh name="front_${lr}_steer"
                     color="White"
                     origin_rpy="0 0 0"
                     origin_xyz="${translateX * chassis_x_origin_to_steer_x_origin}
                                 ${translateY * chassis_y_origin_to_steer_y_origin}
                                 ${(chassis_height/2) + chassis_z_origin_to_steer_z_origin}"
                     mass="1.0"
                     ixx="0.0001" ixy="0.0" ixz="0.0"
                     iyy="0.0001" iyz="0.0"
                     izz="0.0001"
                     meshfile="package://rover_desc_pkg/meshes/rover_steer.dae"
                     meshscale="1 1 1"/>

        <gazebo reference="front_${lr}_steer">
            <visual name="front_${lr}_steer_visual">
                <material>
                    <ambient>0.5 0.5 0.5 1.0</ambient>
                    <specular>0.8 0.8 0.8 0.1</specular>
                    <diffuse>1.0 1.0 1.0 1.0</diffuse>
                </material>
            </visual>
            <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <!-- Transmission is important to link the joints and the controller -->
        <!-- <transmission name="front_${lr}_steer_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="front_${lr}_steer_joint"/>
            <actuator name="front_${lr}_steer_joint_motor">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission> -->
    </xacro:macro>

    <xacro:macro name="steer_r" params="lr parent translateX translateY"> <!-- lr: left, right -->
        <m_joint name="${parent}__rear_${lr}_steer" type="fixed"
                 axis_xyz="0 0 0"
                 origin_rpy="0 0 0" origin_xyz="0 0 0"
                 parent="${parent}" child="rear_${lr}_steer"
                 limit_e="0" limit_l="0" limit_u="0" limit_v="0"/>

        <m_link_mesh name="rear_${lr}_steer"
                     color="White"
                     origin_rpy="0 0 0"
                     origin_xyz="${translateX * (chassis_x_origin_to_steer_x_origin + 0.063)}
                                 ${translateY * chassis_y_origin_to_steer_y_origin}
                                 ${(chassis_height/2) + chassis_z_origin_to_steer_z_origin}"
                     mass="1.0"
                     ixx="0.0001" ixy="0.0" ixz="0.0"
                     iyy="0.0001" iyz="0.0"
                     izz="0.0001"
                     meshfile="package://rover_desc_pkg/meshes/rover_steer.dae"
                     meshscale="1 1 1"/>

        <gazebo reference="rear_${lr}_steer">
            <visual name="rear_${lr}_steer_visual">
                <material>
                    <ambient>0.5 0.5 0.5 1.0</ambient>
                    <specular>0.8 0.8 0.8 0.1</specular>
                    <diffuse>1.0 1.0 1.0 1.0</diffuse>
                </material>
            </visual>
            <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <!-- Transmission is important to link the joints and the controller -->
        <!-- <transmission name="rear_${lr}_steer_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="rear_${lr}_steer_joint"/>
            <actuator name="rear_${lr}_steer_joint_motor">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission> -->
    </xacro:macro>
</robot>
