<?xml version="1.0"?>
<robot name="wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Begin - Include -->
    <xacro:include filename="$(find rover_desc_pkg)/urdf/robot_parameters.xacro"/>
    <xacro:include filename="$(find rover_desc_pkg)/urdf/links_joints.xacro"/>
    <!-- End - Include -->

    <xacro:macro name="wheel" params="fr lr parent translateX translateY"> <!-- fr: front, rear; lr: left, right -->
        <m_joint name="${r_link_01_name}__${fr}_${lr}_wheel" type="fixed"
                 axis_xyz="0 0 0"
                 origin_rpy="0 0 0" origin_xyz="0 0 0"
                 parent="${parent}" child="${fr}_${lr}_wheel"
                 limit_e="0" limit_l="0" limit_u="0" limit_v="0"/>

        <m_link_mesh name="${fr}_${lr}_wheel"
                     color="Black"
                     origin_rpy="0 0 0" origin_xyz="${translateX * base_x_origin_to_wheel_origin} ${translateY * base_y_origin_to_wheel_origin} ${wheel_radius/2}"
                     mass="1.0"
                     ixx="0.0001" ixy="0.0" ixz="0.0"
                     iyy="0.0001" iyz="0.0"
                     izz="0.0001"
                     meshfile="package://rover_desc_pkg/meshes/rover_wheel.dae"
                     meshscale="1 1 1"/>

        <gazebo reference="${fr}_${lr}_wheel">
            <material>Gazebo/Black</material>
            <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <!-- Transmission is important to link the joints and the controller -->
        <!-- <transmission name="${fr}_${lr}_wheel_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${fr}_${lr}_wheel_joint"/>
            <actuator name="${fr}_${lr}_wheel_joint_motor">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission> -->
    </xacro:macro>
</robot>
