# arm_joint_ctrlr_params.yaml
#
# This file defines joint controller parameter values used for simulating a
# 5 DOF arm.
#
#
# Publish the joint states to joint_states.
arm_joint_state_ctrlr:
  type: joint_state_controller/JointStateController
  publish_rate: 30

arm_link_01_ctrlr:
  joint: arm_base_link__arm_link_01_joint
  type: effort_controllers/JointPositionController
  pid: {p: 100.0, i: 0.01, d: 10.0}
arm_link_02_ctrlr:
  joint: arm_link_01__arm_link_02_joint
  type: effort_controllers/JointPositionController
  pid: {p: 100.0, i: 0.01, d: 10.0}
arm_link_03_ctrlr:
  joint: arm_link_02__arm_link_03_joint
  type: effort_controllers/JointPositionController
  pid: {p: 100.0, i: 0.01, d: 10.0}
arm_link_03a_ctrlr:
  joint: arm_link_03__arm_link_03a_joint
  type: effort_controllers/JointPositionController
  pid: {p: 100.0, i: 0.01, d: 10.0}
arm_link_04_ctrlr:
  joint: arm_link_03a__arm_link_04_joint
  type: effort_controllers/JointPositionController
  pid: {p: 100.0, i: 0.01, d: 10.0}
