joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 30

rover_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - chassis_link__front_left_steer
    - chassis_link__front_right_steer
    - front_left_steer__front_left_wheel
    - front_right_steer__front_right_wheel
    - rear_left_steer__rear_left_wheel
    - rear_right_steer__rear_right_wheel

  constraints:
    goal_time: 5.0
    stopped_velocity_tolerance: 1.0
    chassis_link__front_left_steer:
      goal: 0.5
    chassis_link__front_right_steer:
      goal: 0.5
    front_left_steer__front_left_wheel:
      goal: 0.5
    front_right_steer__front_right_wheel:
      goal: 0.5
    rear_left_steer__rear_left_wheel:
      goal: 0.5
    rear_right_steer__rear_right_wheel:
      goal: 0.5

  gains:
    chassis_link__front_left_steer: {p: 200.0, i: 0.01, d: 1.0}
    chassis_link__front_right_steer: {p: 200.0, i: 0.01, d: 1.0}
    front_left_steer__front_left_wheel: {p: 2.5, i: 0.0, d: 0.0, i_clamp: 10.0}
    front_right_steer__front_right_wheel: {p: 2.5, i: 0.0, d: 0.0, i_clamp: 10.0}
    rear_left_steer__rear_left_wheel: {p: 2.5, i: 0.0, d: 0.0, i_clamp: 10.0}
    rear_right_steer__rear_right_wheel: {p: 2.5, i: 0.0, d: 0.0, i_clamp: 10.0}

  state_publish_rate:  30            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 1.0      # Override default

arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_foot_cyl__arm_link_01_joint
    - arm_link_01__arm_link_02_joint
    - arm_link_02__arm_link_03_joint
    - arm_link_03__arm_link_03a_joint
    - arm_link_03a__arm_link_04_joint

  constraints:
    goal_time: 5.0
    stopped_velocity_tolerance: 1.0
    arm_foot_cyl__arm_link_01_joint:
      goal: 0.5
    arm_link_01__arm_link_02_joint:
      goal: 0.5
    arm_link_02__arm_link_03_joint:
      goal: 0.5
    arm_link_03__arm_link_03a_joint:
      goal: 0.5
    arm_link_03a__arm_link_04_joint:
      goal: 0.5

  gains:
    arm_foot_cyl__arm_link_01_joint: {p: 8.5, i: 0.01, d: 0.0}
    arm_link_01__arm_link_02_joint: {p: 8.5, i: 0.01, d: 0.0}
    arm_link_02__arm_link_03_joint: {p: 8.5, i: 0.01, d: 0.0}
    arm_link_03__arm_link_03a_joint: {p: 8.5, i: 0.01, d: 0.0}
    arm_link_03a__arm_link_04_joint: {p: 8.5, i: 0.01, d: 0.0}

  state_publish_rate:  30            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 1.0      # Override default
