joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 30

arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_foot_cyl__arm_link_01_joint
    - arm_link_01__arm_link_02_joint
    - arm_link_02__arm_link_03_joint
    - arm_link_03__arm_link_03a_joint
    - arm_link_03a__arm_link_04_joint

  constraints:
    goal_time: 5.0
    stopped_velocity_tolerance: 1.0
    arm_foot_cyl__arm_link_01_joint:
      goal: 0.5
    arm_link_01__arm_link_02_joint:
      goal: 0.5
    arm_link_02__arm_link_03_joint:
      goal: 0.5
    arm_link_03__arm_link_03a_joint:
      goal: 0.5
    arm_link_03a__arm_link_04_joint:
      goal: 0.5

  gains:
    arm_foot_cyl__arm_link_01_joint: {p: 8.5, i: 0.01, d: 0.0}
    arm_link_01__arm_link_02_joint: {p: 8.5, i: 0.01, d: 0.0}
    arm_link_02__arm_link_03_joint: {p: 8.5, i: 0.01, d: 0.0}
    arm_link_03__arm_link_03a_joint: {p: 8.5, i: 0.01, d: 0.0}
    arm_link_03a__arm_link_04_joint: {p: 8.5, i: 0.01, d: 0.0}

  state_publish_rate:  30            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 1.0      # Override default
