<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Begin - Include -->
  <xacro:include filename="$(find rover_arm_desc_pkg)/urdf/arm_parameters.xacro"/>
  <xacro:include filename="$(find rover_desc_pkg)/urdf/rover_parameters.xacro"/>
  <xacro:include filename="$(find rover_desc_pkg)/urdf/links_joints.xacro"/>
  <!-- End - Include -->

  <!-- Links -->
  <xacro:macro name="arm_link" params="name parent length width height link_xyz link_rpy joint_xyz joint_rpy axis_xyz lim_l lim_u">
    <!-- Joint for link movement -->
    <xacro:m_joint_rev name="${parent}__${name}_joint"
                       axis_xyz="${axis_xyz}"
                       origin_rpy="${joint_rpy}" origin_xyz="${joint_xyz}"
                       parent="${parent}" child="${name}"
                       limit_e="1000.0" limit_l="${lim_l}" limit_u="${lim_u}" limit_v="1"
                       dynamics_d="50" dynamics_f="1"/>

    <!-- Link 01 -->
    <xacro:m_link_cylinder name="${name}"
                           color="darkgray"
                           origin_rpy="${link_rpy}"
                           origin_xyz="${link_xyz}"
                           radius="0.05"
                           length="0.06"
                           mass="1.0"
                           ixx="0.0001" ixy="0.0" ixz="0.0"
                           iyy="0.0001" iyz="0.0"
                           izz="0.0001"/>

    <gazebo reference="${name}">
      <material>Gazebo/Gray</material>
    </gazebo>

    <!-- fixed joint -->
    <xacro:m_joint_fixed name="${name}__${name}_box_joint"
                         origin_rpy="0 0 0" origin_xyz="0 0 0"
                         parent="${name}" child="${name}_box"/>

    <!-- Link Arm -->
    <xacro:m_link_box name="${name}_box"
                      color="white"
                      origin_rpy="0 0 0" origin_xyz="${length/2 + 0.045} 0 0"
                      size="${length} ${width} ${height}"/>

    <gazebo reference="${name}_box">
      <material>Gazebo/Silver</material>
    </gazebo>
  </xacro:macro>
</robot>
