<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="a_link_00_name" value="arm_footprint"/>
  <xacro:property name="a_link_0a_name" value="arm_foot_cyl"/>
  <xacro:property name="a_link_01_name" value="arm_link_01"/>
  <xacro:property name="a_link_02_name" value="arm_link_02"/>
  <xacro:property name="a_link_03_name" value="arm_link_03"/>
  <xacro:property name="a_link_03a_name" value="arm_link_03a"/>
  <xacro:property name="a_link_04_name" value="arm_link_04"/>

  <!-- All the units are in m-kg-s-radians unit system -->
  <xacro:property name="M_PI" value="3.141592653"/>
  <xacro:property name="DEG_TO_RAD" value="0.017453293"/>

  <!-- Footprint dimensions -->
  <xacro:property name="arm_foot_cyl_radius" value="0.02"/>
  <xacro:property name="arm_foot_cyl_height" value="0.02"/>

  <!-- Footprint position coordinates -->
  <xacro:property name="world_x_origin_to_arm_x_origin" value="${chassis_length/2 + arm_foot_cyl_radius}"/> <!-- Distance from world origin to mount point in X direction -->
  <xacro:property name="world_y_origin_to_arm_y_origin" value="-0.122"/> <!-- Distance from world origin to mount point in Y direction -->
  <xacro:property name="world_z_origin_to_arm_z_origin" value="${0.56665-arm_foot_cyl_height}"/> <!-- Distance from world origin to mount point in Z direction -->

  <!-- Arm joints -->
  <xacro:property name="arm_link_cyl_radius" value="0.05"/>
  <xacro:property name="arm_link_cyl_height" value="0.06"/>
  <xacro:property name="arm_link_cyl_mass" value="0.2"/> <!-- in Kg -->

  <!-- Arm Link 01 dimensions -->
  <xacro:property name="arm_link01_x" value="0.080"/>
  <xacro:property name="arm_link01_y" value="0.125"/>
  <xacro:property name="arm_link01_z" value="0.400"/>
  <xacro:property name="arm_link01_m" value="0.2"/> <!-- in Kg -->

  <!-- Arm Link 01 translations -->
  <xacro:property name="arm_link01_x_trans" value="0.0000"/>
  <xacro:property name="arm_link01_y_trans" value="0.1050"/>
  <xacro:property name="arm_link01_z_trans" value="0.0000"/>

  <!-- Arm Link 02 dimensions -->
  <xacro:property name="arm_link02_x" value="0.0384"/>
  <xacro:property name="arm_link02_y" value="0.0340"/>
  <xacro:property name="arm_link02_z" value="0.0485"/>
  <xacro:property name="arm_link02_m" value="0.2"/> <!-- in Kg -->

  <!-- Arm Link 02 translations -->
  <xacro:property name="arm_link02_x_trans" value="0.0147"/>
  <xacro:property name="arm_link02_y_trans" value="0.0000"/>
  <xacro:property name="arm_link02_z_trans" value="-0.025"/>

  <!-- Arm Link 03 dimensions -->
  <xacro:property name="arm_link03_x" value="0.0280"/>
  <xacro:property name="arm_link03_y" value="0.0650"/>
  <xacro:property name="arm_link03_z" value="0.0485"/>
  <xacro:property name="arm_link03_m" value="0.2"/> <!-- in Kg -->

  <!-- Arm Link 03 translations -->
  <xacro:property name="arm_link03_x_trans" value="0.0000"/>
  <xacro:property name="arm_link03_y_trans" value="0.0000"/>
  <xacro:property name="arm_link03_z_trans" value="-0.095"/>

  <!-- Arm Link 03a dimensions -->
  <xacro:property name="arm_link03a_x" value="0.0200"/>
  <xacro:property name="arm_link03a_y" value="0.0200"/>
  <xacro:property name="arm_link03a_z" value="0.1900"/>
  <xacro:property name="arm_link03a_m" value="0.2"/> <!-- in Kg -->

  <!-- Arm Link 03a translations -->
  <xacro:property name="arm_link03a_x_trans" value="0.0000"/>
  <xacro:property name="arm_link03a_y_trans" value="0.0000"/>
  <xacro:property name="arm_link03a_z_trans" value="${-arm_link03a_z/2}"/>

  <!-- Arm Link 04 dimensions -->
  <xacro:property name="arm_link04_x" value="0.0200"/>
  <xacro:property name="arm_link04_y" value="0.0200"/>
  <xacro:property name="arm_link04_z" value="0.0940"/>
  <xacro:property name="arm_link04_m" value="0.2"/> <!-- in Kg -->

  <!-- Arm Link 04 translations -->
  <xacro:property name="arm_link04_x_trans" value="0.0200"/>
  <xacro:property name="arm_link04_y_trans" value="0.0000"/>
  <xacro:property name="arm_link04_z_trans" value="${-arm_link04_z/2}"/>

  <!-- joints translations -->
  <xacro:property name="link01_link02_x" value="0.0825"/>
  <xacro:property name="link01_link02_y" value="0.1050"/>
  <xacro:property name="link01_link02_z" value="0.0000"/>

  <xacro:property name="link02_link03_x" value="0.0150"/>
  <xacro:property name="link02_link03_y" value="0.0000"/>
  <xacro:property name="link02_link03_z" value="-0.023"/>

  <xacro:property name="link03_link03a_x" value="0.0000"/>
  <xacro:property name="link03_link03a_y" value="0.0000"/>
  <xacro:property name="link03_link03a_z" value="${arm_link03_z_trans}"/>

  <xacro:property name="link03a_link04_x" value="0.0000"/>
  <xacro:property name="link03a_link04_y" value="0.0000"/>
  <xacro:property name="link03a_link04_z" value="${-arm_link03a_z}"/>
</robot>
