<?xml version="1.0"?>
<robot name="rover_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Begin - Include -->
  <xacro:include filename="$(find rover_arm_desc_pkg)/urdf/arm_parameters.xacro"/>
  <xacro:include filename="$(find rover_desc_pkg)/urdf/rover_parameters.xacro"/>
  <xacro:include filename="$(find rover_desc_pkg)/urdf/links_joints.xacro"/>
  <!-- End - Include -->

  <!-- Begin - Robot Description -->
  <!-- Chassis footprint -->
  <xacro:m_link_box name="${a_link_00_name}"
                    color="white"
                    origin_rpy="0 0 0" origin_xyz="${chassis_length/2} -0.122 0.562"
                    size="0.0001 0.0001 0.0001"/>

  <gazebo reference="${r_link_00_name}">
    <material>Gazebo/White</material>
  </gazebo>

  <!-- Link 01 -->
  <xacro:m_link_cylinder name="${a_link_01_name}"
                         color="gray"
                         origin_rpy="0 0 0"
                         origin_xyz="0 0 0"
                         radius="0.02"
                         length="0.2"
                         mass="1.0"
                         ixx="0.0001" ixy="0.0" ixz="0.0"
                         iyy="0.0001" iyz="0.0"
                         izz="0.0001"/>

  <gazebo reference="${r_link_01_name}">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <!-- Link 00 and Link 01 joint -->
  <xacro:m_joint_fixed name="${a_link_00_name}__${a_link_01_name}"
                       origin_rpy="0 0 0" origin_xyz="0 0 0"
                       parent="${a_link_00_name}" child="${a_link_01_name}"/>
  <!-- End - Robot Description -->
</robot>
